-- ============================================================================
-- DARVIK — dados reais migrados do sistema publicado (gerado automaticamente)
-- ============================================================================
-- IMPORTANTE: rode isto DEPOIS de:
--   1) supabase/schema.sql (cria as tabelas)
--   2) supabase/seed-users.mjs (cria as contas de login e a tabela profiles —
--      este arquivo abaixo referencia usuários pelo "legacy_id" que aquele
--      script cria; se você rodar este arquivo antes, vai dar erro de chave
--      estrangeira.
-- ============================================================================

-- Categorias
insert into categories (id, name) values ('cat-1', 'vestidos') on conflict (id) do update set name=excluded.name;
insert into categories (id, name) values ('cat-2', 'Jaqueta') on conflict (id) do update set name=excluded.name;
insert into categories (id, name) values ('cat-3', 'Kit de Chave') on conflict (id) do update set name=excluded.name;

-- Fornecedores
insert into suppliers (id, name, contact, phone) values ('sup-1', 'Ingrid', 'Ingrid482@gmail.com.br', '119657-7654') on conflict (id) do update set name=excluded.name, contact=excluded.contact, phone=excluded.phone;
insert into suppliers (id, name, contact, phone) values ('sup-2', 'Yasmin', 'ycbrito2022@gmail.com', '11997085306') on conflict (id) do update set name=excluded.name, contact=excluded.contact, phone=excluded.phone;

-- Clientes

-- Produtos
insert into products (id, sku, name, category_id, brand, price, variations, created_at) values ('prod-1', 'SKU-0001', 'Vestido Midi', 'cat-1', 'Brito Modas', 45, '[{"id": "var-r6izeni", "name": "Preto"}, {"id": "var-m60g10n", "name": "Branco"}, {"id": "var-7q357hv", "name": "Bege"}]'::jsonb, to_timestamp(1788136843619::double precision/1000.0)) on conflict (id) do update set sku=excluded.sku, name=excluded.name, category_id=excluded.category_id, brand=excluded.brand, price=excluded.price, variations=excluded.variations;
insert into products (id, sku, name, category_id, brand, price, variations, created_at) values ('prod-2', 'SKU-0002', 'Jaqueta Cotele', 'cat-2', 'Brito modas', 80, '[{"id": "var-buhzdrn", "name": "Preto"}, {"id": "var-bu60yff", "name": "Branco"}, {"id": "var-5r18n9l", "name": "Nude"}, {"id": "var-vjro1vb", "name": "Vinho"}, {"id": "var-mlayrq8", "name": "Marrom"}]'::jsonb, to_timestamp(1789388761630::double precision/1000.0)) on conflict (id) do update set sku=excluded.sku, name=excluded.name, category_id=excluded.category_id, brand=excluded.brand, price=excluded.price, variations=excluded.variations;
insert into products (id, sku, name, category_id, brand, price, variations, created_at) values ('prod-3', 'SKU-0003', 'Kit de Chave - Yaxun 898', 'cat-3', 'Yaxun', 36, '[{"id": "var-rxsx4ze", "name": "6 em 1"}]'::jsonb, to_timestamp(1789437747719::double precision/1000.0)) on conflict (id) do update set sku=excluded.sku, name=excluded.name, category_id=excluded.category_id, brand=excluded.brand, price=excluded.price, variations=excluded.variations;

-- Localizações
insert into locations (id, corridor, shelf, level, capacity, code, qr_payload) values ('loc-1', 'A', '3', '1', 30, 'A-3-1', 'LOC:loc-1') on conflict (id) do update set corridor=excluded.corridor, shelf=excluded.shelf, level=excluded.level, capacity=excluded.capacity, code=excluded.code, qr_payload=excluded.qr_payload;
insert into locations (id, corridor, shelf, level, capacity, code, qr_payload) values ('loc-2', 'B', '04', '2', 150, 'B-04-2', 'LOC:loc-2') on conflict (id) do update set corridor=excluded.corridor, shelf=excluded.shelf, level=excluded.level, capacity=excluded.capacity, code=excluded.code, qr_payload=excluded.qr_payload;

-- Estoque (quantidade por produto/variação/localização)
insert into stock (id, product_id, variation_id, location_id, quantity) values ('stock-1', 'prod-1', 'var-r6izeni', 'loc-1', 20) on conflict (id) do update set quantity=excluded.quantity;

-- Movimentações de estoque
insert into stock_movements (id, type, product_id, variation_id, quantity, location_id, user_id, user_name, "timestamp", ref_type, ref_id, note) values ('mov-1', 'entrada', 'prod-1', 'var-r6izeni', 20, 'loc-1', 'u1', 'Administrador', to_timestamp(1788229093162::double precision/1000.0), 'recebimento', 'po-1', 'Armazenagem') on conflict (id) do nothing;

-- Pedidos de compra
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-1', 'OC-0001', 'sup-1', '[{"id": "poi-1", "isNew": false, "productId": "prod-1", "variationId": "var-r6izeni", "newName": "", "newCategoryId": null, "qtyOrdered": 20, "qtyReceived": 20}]'::jsonb, 'CONCLUIDO', to_timestamp(1788480000000::double precision/1000.0), to_timestamp(1788229005472::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-2', 'OC-0002', 'sup-1', '[{"id": "poi-2", "isNew": false, "productId": "prod-1", "variationId": "var-r6izeni", "newName": "", "newCategoryId": null, "qtyOrdered": 20, "qtyReceived": 20}, {"id": "poi-3", "isNew": false, "productId": "prod-1", "variationId": "var-7q357hv", "newName": "", "newCategoryId": null, "qtyOrdered": 50, "qtyReceived": 50}]'::jsonb, 'RECEBIDO', to_timestamp(1788998400000::double precision/1000.0), to_timestamp(1788621813450::double precision/1000.0), 'user-1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-3', 'OC-0003', 'sup-1', '[{"id": "poi-4", "isNew": false, "productId": "prod-1", "variationId": "var-m60g10n", "newName": "", "newCategoryId": null, "qtyOrdered": 5, "qtyReceived": 5}]'::jsonb, 'RECEBIDO', to_timestamp(1789256817332::double precision/1000.0), to_timestamp(1788824817332::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-4', 'OC-0004', 'sup-1', '[{"id": "poi-5", "isNew": false, "productId": "prod-1", "variationId": "var-m60g10n", "newName": "", "newCategoryId": null, "qtyOrdered": 1200, "qtyReceived": 1200}]'::jsonb, 'RECEBIDO', to_timestamp(1789344000000::double precision/1000.0), to_timestamp(1789318154882::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-5', 'OC-0005', 'sup-1', '[{"id": "poi-6", "isNew": false, "productId": "prod-1", "variationId": null, "newName": "", "newCategoryId": null, "qtyOrdered": 20, "qtyReceived": 20}]'::jsonb, 'RECEBIDO', to_timestamp(1789344000000::double precision/1000.0), to_timestamp(1789350280967::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-6', 'OC-0006', 'sup-1', '[{"id": "poi-7", "isNew": false, "productId": "prod-2", "variationId": "var-buhzdrn", "newName": "", "newCategoryId": null, "qtyOrdered": 30, "qtyReceived": 30}]'::jsonb, 'RECEBIDO', to_timestamp(1789430400000::double precision/1000.0), to_timestamp(1789416727605::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into purchase_orders (id, code, supplier_id, items, status, expected_date, created_at, created_by) values ('po-7', 'OC-0007', 'sup-2', '[{"id": "poi-8", "isNew": false, "productId": "prod-3", "variationId": "var-rxsx4ze", "newName": "", "newCategoryId": null, "qtyOrdered": 8, "qtyReceived": 8}]'::jsonb, 'RECEBIDO', to_timestamp(1789689600000::double precision/1000.0), to_timestamp(1789437802773::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;

-- Tarefas de armazenagem
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-1', 'po-1', 'poi-1', 'prod-1', 'var-r6izeni', 0, 'loc-1', 'CONCLUIDO') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-2', 'po-2', 'poi-2', 'prod-1', 'var-r6izeni', 20, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-3', 'po-2', 'poi-3', 'prod-1', 'var-7q357hv', 50, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-4', 'po-3', 'poi-4', 'prod-1', 'var-m60g10n', 5, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-5', 'po-4', 'poi-5', 'prod-1', 'var-m60g10n', 1200, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-6', 'po-5', 'poi-6', 'prod-1', NULL, 20, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-7', 'po-6', 'poi-7', 'prod-2', 'var-buhzdrn', 30, 'loc-1', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;
insert into storage_tasks (id, po_id, po_item_id, product_id, variation_id, qty_pending, suggested_location_id, status) values ('storage-8', 'po-7', 'poi-8', 'prod-3', 'var-rxsx4ze', 8, 'loc-2', 'PENDENTE') on conflict (id) do update set qty_pending=excluded.qty_pending, status=excluded.status;

-- Pedidos de venda
insert into sales_orders (id, code, channel, customer_id, items, status, priority, created_at, created_by) values ('so-1', 'PED-0001', 'LOJA', NULL, '[{"id": "soi-1", "productId": "prod-1", "variationId": "var-r6izeni", "qty": 2, "locationId": null, "separated": false, "conferred": false}]'::jsonb, 'AGUARDANDO_SEPARACAO', 'ALTA', to_timestamp(1788231114779::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into sales_orders (id, code, channel, customer_id, items, status, priority, created_at, created_by) values ('so-2', 'PED-0002', 'LOJA', NULL, '[{"id": "soi-2", "productId": "prod-1", "variationId": null, "qty": 0, "locationId": null, "separated": true, "conferred": false}]'::jsonb, 'EM_CONFERENCIA', 'ALTA', to_timestamp(1788403889151::double precision/1000.0), 'user-1') on conflict (id) do update set items=excluded.items, status=excluded.status;
insert into sales_orders (id, code, channel, customer_id, items, status, priority, created_at, created_by) values ('so-3', 'PED-0003', 'LOJA', NULL, '[{"id": "soi-3", "productId": "prod-1", "variationId": "var-r6izeni", "qty": 2, "locationId": null, "separated": false, "conferred": false}]'::jsonb, 'AGUARDANDO_SEPARACAO', 'ALTA', to_timestamp(1789388931755::double precision/1000.0), 'u1') on conflict (id) do update set items=excluded.items, status=excluded.status;

-- Pagamentos

-- Expedições

-- Histórico / auditoria
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-41', to_timestamp(1789438456099::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou usuário', 'usuario', 'user-3', 'Yasmin') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-40', to_timestamp(1789437981348::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-7', 'OC-0007') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-39', to_timestamp(1789437802773::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-7', 'OC-0007') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-38', to_timestamp(1789437747719::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou produto', 'produto', 'prod-3', 'Kit de Chave - Yaxun 898') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-37', to_timestamp(1789437636421::double precision/1000.0), 'u1', 'Administrador', 'Criou categoria', 'categoria', 'cat-3', 'Kit de Chave') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-36', to_timestamp(1789437558392::double precision/1000.0), 'u1', 'Administrador', 'Editou fornecedor', 'fornecedor', 'sup-2', 'Yasmin') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-35', to_timestamp(1789437529585::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou fornecedor', 'fornecedor', 'sup-2', 'Yasmin') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-34', to_timestamp(1789437409434::double precision/1000.0), 'u1', 'Administrador', 'Criou localização', 'localizacao', 'loc-2', 'B-04-2') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-33', to_timestamp(1789416759065::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-6', 'OC-0006') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-32', to_timestamp(1789416727605::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-6', 'OC-0006') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-31', to_timestamp(1789416690732::double precision/1000.0), 'u1', 'Administrador', 'Editou usuário', 'usuario', 'user-2', 'Messias') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-30', to_timestamp(1789400402735::double precision/1000.0), 'u1', 'Administrador', 'Editou usuário', 'usuario', 'user-2', 'Messias') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-29', to_timestamp(1789397404421::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou usuário', 'usuario', 'user-2', 'Messias') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-28', to_timestamp(1789388931755::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de venda', 'pedido_venda', 'so-3', 'PED-0003') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-27', to_timestamp(1789388761630::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou produto', 'produto', 'prod-2', 'Jaqueta Cotele') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-26', to_timestamp(1789388696071::double precision/1000.0), 'u1', 'Administrador', 'Criou categoria', 'categoria', 'cat-2', 'Jaqueta') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-25', to_timestamp(1789350364544::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-5', 'OC-0005') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-24', to_timestamp(1789350350895::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-4', 'OC-0004') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-23', to_timestamp(1789350280967::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-5', 'OC-0005') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-22', to_timestamp(1789318154882::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-4', 'OC-0004') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-21', to_timestamp(1788827585045::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-3', 'OC-0003') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-20', to_timestamp(1788824817332::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-3', 'OC-0003 — pedido de demonstração (5 un. de Vestido Midi — Branco) criado para você testar a tela de Recebimento; pode receber normalmente ou ajustar/ignorar depois.') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-19', to_timestamp(1788819162467::double precision/1000.0), 'u1', 'Administrador', 'Concluiu pedido de compra', 'pedido_compra', 'po-1', 'OC-0001') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-18', to_timestamp(1788810091681::double precision/1000.0), 'u1', 'Administrador', 'Migração de login', 'sistema', NULL, 'Usuários existentes receberam login e senha temporária ("1234") — trocar em Usuários assim que possível.') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-17', to_timestamp(1788621907076::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Confirmou recebimento', 'pedido_compra', 'po-2', 'OC-0002') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-16', to_timestamp(1788621813450::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Criou pedido de compra', 'pedido_compra', 'po-2', 'OC-0002') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-15', to_timestamp(1788621600523::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Editou produto', 'produto', 'prod-1', 'Vestido Midi') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-14', to_timestamp(1788403898885::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Concluiu separação', 'pedido_venda', 'so-2', 'PED-0002') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-13', to_timestamp(1788403896684::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Iniciou separação', 'pedido_venda', 'so-2', 'PED-0002') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-12', to_timestamp(1788403889151::double precision/1000.0), 'user-1', 'INVENTRA.OFICIAL', 'Criou pedido de venda', 'pedido_venda', 'so-2', 'PED-0002') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-11', to_timestamp(1788310280599::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou usuário', 'usuario', 'user-1', 'INVENTRA.OFICIAL') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-10', to_timestamp(1788231114779::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de venda', 'pedido_venda', 'so-1', 'PED-0001') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-9', to_timestamp(1788229093162::double precision/1000.0), 'u1', 'Administrador', 'Armazenou item', 'estoque', 'prod-1', '20 un. em A-3-1') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-8', to_timestamp(1788229038143::double precision/1000.0), 'u1', 'Administrador', 'Confirmou recebimento', 'pedido_compra', 'po-1', 'OC-0001') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-7', to_timestamp(1788229005472::double precision/1000.0), 'u1', 'Administrador', 'Criou pedido de compra', 'pedido_compra', 'po-1', 'OC-0001') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-6', to_timestamp(1788228957325::double precision/1000.0), 'u1', 'Administrador', 'Editou produto', 'produto', 'prod-1', 'Vestido Midi') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-5', to_timestamp(1788228938055::double precision/1000.0), 'u1', 'Administrador', 'Criou localização', 'localizacao', 'loc-1', 'A-3-1') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-4', to_timestamp(1788228883847::double precision/1000.0), 'u1', 'Administrador', 'Criou categoria', 'categoria', 'cat-1', 'vestidos') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-3', to_timestamp(1788228869386::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou fornecedor', 'fornecedor', 'sup-1', 'Ingrid') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-2', to_timestamp(1788136895543::double precision/1000.0), 'u1', 'Administrador', 'Editou produto', 'produto', 'prod-1', 'Vestido Midi') on conflict (id) do nothing;
insert into audit_log (id, "timestamp", user_id, user_name, action, entity_type, entity_id, details) values ('audit-1', to_timestamp(1788136843619::double precision/1000.0), 'u1', 'Administrador', 'Cadastrou produto', 'produto', 'prod-1', 'Vestido Midi') on conflict (id) do nothing;

-- Contadores de código (para os próximos SKU-000x, OC-000x, PED-000x etc.)
update org_meta set org_name = 'DARVIK', seq = '{"user": 4, "cat": 4, "prod": 4, "loc": 3, "stock": 2, "mov": 2, "sup": 3, "cus": 1, "po": 8, "poi": 9, "so": 4, "soi": 4, "pay": 1, "ship": 1, "audit": 42, "alert": 1, "storage": 9}'::jsonb where id = 'main';
